Feature/send email
geekcamp-vol11-team30/backend pull request #14
Opened 2023-09-21 02:24 UTC by TT-RR

## 変更の概要

#11 
SendEmail関数の追加

## なぜこの変更をするのか

全員の回答が完了したときメールを通知する

## 課題

メールのタイトルと本文は仮

## 備考
レビューお願いします！

2023-09-21 03:46 UTC, Yuta123456 commented on util/util.go
> +func SendMail(id ulid.ULID, password, targetAddrs string) error {
`sendMail`関数では、`password`を引数にするんではなく、恐らくこの関数内で環境変数からとってくるのが良いと思います。`password`というメールを送る際にしか使わない情報はこの関数で閉じさせるのが良いです。
あと`id`はなんのidですか？
@TT-RR

2023-09-21 03:52 UTC, TT-RR commented on util/util.go
> +func SendMail(id ulid.ULID, password, targetAddrs string) error {
#11 
に「SendEmailを用意して，ID/PASSWORD/EMAIL ADDRESSをとって，SMTPで送信できるようにしたい」って書いてあったので、id書きました

2023-09-21 03:54 UTC, Yuta123456 commented on util/util.go
> +func SendMail(id ulid.ULID, password, targetAddrs string) error {
あー。なるほど、高橋さんの意図を理解しました。`util`に置くつもりなんですね、了解です

2023-09-21 04:44 UTC, TT-RR commented on util/util.go
> +func SendMail(id ulid.ULID, password, targetAddrs string) error {
MakeRandomStrで一意なパスワードを生成させるってことですか？

2023-09-22 03:19 UTC, TAK848 commented on util/util.go
> +func SendMail(id ulid.ULID, password, targetAddrs string) error {
os.GetEnvではなく，configに設定してほしいです！

2023-09-22 03:21 UTC, TAK848 requested changes

2023-09-22 03:21 UTC, TAK848 commented on util/util.go
> +		"確認してください！\n") // メールの本文
utilにドメインの内容が入ってしまっているので，できればtitleとbodyは引数にしたいかな…

2023-09-22 03:21 UTC, TAK848 commented on util/util.go
> +func SendMail(id ulid.ULID, targetAddrs string) error {
このidって引数は何ですかね…？

2023-09-22 03:35 UTC, TT-RR commented on util/util.go
> +		"確認してください！\n") // メールの本文
「SendEmailを用意して，ID/PASSWORD/EMAIL ADDRESSをとって，SMTPで送信できるようにしたい」って書いてあったので、id書いたんですが…

2023-09-22 03:36 UTC, TT-RR commented on util/util.go
> +func SendMail(id ulid.ULID, targetAddrs string) error {
「SendEmailを用意して，ID/PASSWORD/EMAIL ADDRESSをとって，SMTPで送信できるようにしたい」って書いてあったので、id書きました

2023-09-22 03:48 UTC, TAK848 commented on util/util.go
> +func SendMail(id ulid.ULID, targetAddrs string) error {
IDというのはSMTPのIDで，ちょっと表記が良くなかったので申し訳ないです！

送信元のメアド
送信用のサーバーアドレス
などです...!

Config経由でとってほしい(ULIDは全く関係ないです)

2023-09-22 04:16 UTC, TT-RR commented on util/util.go
> +func SendMail(id ulid.ULID, targetAddrs string) error {
config使ったことなくて分からないんですけど、どうやったら指定できますか？

### 追加したところ
config.go
```
type Config struct {
	Port                 int    `env:"PORT" envDefault:"80"`
	Env                  string `env:"ENV" envDefault:"dev"`
	BaseURL              string `env:"BASE_URL" envDefault:"http://localhost:8080"`
	SecretKey            string `env:"SECRET_KEY" envDefault:"secret"`
	AccessExpireMinutes  int    `env:"ACCESS_TOKEN_EXPIRE_MINUTES" envDefault:"5"`
	RefreshExpireMinutes int    `env:"REFRESH_TOKEN_EXPIRE_MINUTES" envDefault:"43200"`
	MySQL                MySQL  `envPrefix:"MYSQL_"`
	OAuth                OAuth  `envPrefix:"OAUTH_"`
	CORS                 CORS   `envPrefix:"CORS_"`
	CSRF                 CSRF   `envPrefix:"CSRF_"`
	SMTP                 SMTP   `envPrefix:"SMTP_"`
        -----------------------------------------------
}

type SMTP struct {
	Host     string `env:"HOST" envDefault:"smtp.gmail.com"`
	ID       string `env:"ID" envDefault:"magische@gmail.com"`
	Port     int    `env:"PORT" envDefault:"587"`
	Password string `env:"PASSWORD" envDefault:"passwd"`
}
```

util.go
```
func SendMail(targetAddrs string, title string, body string) error {
    hostname := config.SMTP.Host
    port := config.SMTP.Port
    password := config.SMTP.Password
    from :=  config.SMTP.ID// 送信元のメールアドレス

    recipients := []string{targetAddrs} // 送信先のメールアドレス

    auth := smtp.PlainAuth("", from, password, hostname)
    msg := []byte(strings.ReplaceAll(fmt.Sprintf(
        "To: %s\nSubject: %s\n\n%s", strings.Join(recipients, ","), title, body),
        "\n", "\r\n"))

    // メール送信
    err := smtp.SendMail(fmt.Sprintf("%s:%d", hostname, port), auth, from, recipients, msg)
    if err != nil {
        log.Fatal(err)
    }
    return nil
}
```

2023-09-22 15:31 UTC, closed without merging